######################################################################
# Automatically generated by qmake (3.0) Thu Dec 5 21:44:11 2013
######################################################################

QT += widgets
TEMPLATE = app
TARGET = xmu-calculator
INCLUDEPATH += .

# Input
HEADERS += xmudata.h xmudialog.h
SOURCES += xmudata.cpp xmudialog.cpp main.cpp
RESOURCES += xmudata.qrc
